#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yusuke Makido
# SPDX-License-Identifier: BSD-3-Clause

import sys

ansA = 0
for line in sys.stdin:
    try:
        ansA += int(line)
    except:
        ansA += float(line)

print(ansA)
